lyric_gtf : "/no_backup/rg/references/species/Giardia_muris.5742/GCA_006247105.1/LyRic_complete.gff.gz"
genome_fasta : "/no_backup/rg/references/species/Giardia_muris.5742/GCA_006247105.1/GCA_006247105.1_UU_GM_1.1_genomic.fna.gz"
genome_gtf : "/no_backup/rg/references/species/Giardia_muris.5742/GCA_006247105.1/GCA_006247105.1_UU_GM_1.1_genomic.gff.gz"
species_name : "Giardia_muris.5742"


# Production settings
debug: true
max_cpus: 4  # Reduced for dev mode
max_memory: '16GB'  # Reduced for dev mode

# Optional: Add these if you want to customize the output directory
output_dir: "/no_backup/rg/ileahy/Giardia_muris/ORFsearch"  # Local output directory
geneid_param: "/no_backup/rg/references/species/Giardia_muris.5742/GCA_006247105.1/Giardia_muris_5742_lyric.geneid.edit.param"  # Update to your geneid parameter file location

